version: '3.8'

services:

  beacon-network-frontend:
    build:
      context: ./frontend
    command: node /opt/yarn-v1.22.19/bin/yarn.js start
    container_name: bn-ui
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend/:/frontend/
      - /frontend/node_modules